#if !canImport(ObjectiveC)
import XCTest

extension DarwinNotificationCenterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DarwinNotificationCenterTests = [
        ("testAddObserver", testAddObserver),
        ("testRemoveAllObservers", testRemoveAllObservers),
        ("testRemoveObserver", testRemoveObserver),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DarwinNotificationCenterTests.__allTests__DarwinNotificationCenterTests),
    ]
}
#endif
